/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rscpu2.Jframes;

//import com.mycompany.rscpu2.jframes.*;
import com.mycompany.rscpu2.ErrorChecking;
import com.mycompany.rscpu2.InstructionSet;
import com.mycompany.rscpu2.Scanner;
import com.mycompany.rscpu2.Values.MemoryAddress;
import com.mycompany.rscpu2.Values.Registers;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author John
 */
public class RscpuMenuJframe extends javax.swing.JFrame {

    Scanner scan = new Scanner();
    MemoryAddress memAdd = new MemoryAddress();
    ErrorChecking error = new ErrorChecking();
    Registers reg = new Registers();
    InstructionSet inst = new InstructionSet();
    boolean isError = false;
    boolean isAssemble = false;
    

    /**
     * Creates new form RscpuMenuJframe
     */
    public RscpuMenuJframe() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCode = new javax.swing.JTextArea();
        jButtonRun = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelViewSystems = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelAssemble = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelViewMemory = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelHelp = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelClearMemory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 111, 114));

        jTextAreaCode.setColumns(20);
        jTextAreaCode.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCode);

        jButtonRun.setText("Run");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabelViewSystems.setForeground(new java.awt.Color(153, 255, 255));
        jLabelViewSystems.setText("               View Systems");
        jLabelViewSystems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViewSystemsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelViewSystems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelViewSystems, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabelAssemble.setBackground(new java.awt.Color(255, 255, 0));
        jLabelAssemble.setForeground(new java.awt.Color(153, 255, 255));
        jLabelAssemble.setText("                   Assemble");
        jLabelAssemble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAssembleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAssemble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAssemble, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabelViewMemory.setForeground(new java.awt.Color(153, 255, 255));
        jLabelViewMemory.setText("               View Memory");
        jLabelViewMemory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViewMemoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelViewMemory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelViewMemory, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabelHelp.setForeground(new java.awt.Color(153, 255, 255));
        jLabelHelp.setText("                      Help");
        jLabelHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHelpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabelClearMemory.setForeground(new java.awt.Color(153, 255, 255));
        jLabelClearMemory.setText("              Clear Memory");
        jLabelClearMemory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClearMemoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClearMemory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelClearMemory, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("RSCPU");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("GRATE TASTE BLACK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(52, 52, 52)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jButtonRun))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRun)
                .addGap(41, 41, 41))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed
        // TODO add your handling code here:
        
        if (isError == true || isAssemble == false) {
              JOptionPane.showMessageDialog(this, "Can't run due to assembly Error");
        } else {

            String scannedText = jTextAreaCode.getText();
            scan.getTextScan(scannedText);
            JOptionPane.showMessageDialog(this, "Assembly commands executed <3");
            

            
        }
       


    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jLabelClearMemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMemoryMouseClicked
        // TODO add your handling code here:
        memAdd.clearAddress();
         JOptionPane.showMessageDialog(this, "Memory Cleared");
    }//GEN-LAST:event_jLabelClearMemoryMouseClicked

    private void jLabelViewMemoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewMemoryMouseClicked
        // TODO add your handling code here:
        ViewMemory guiViewMem = new ViewMemory();
        guiViewMem.show();
        // this.hide();
    }//GEN-LAST:event_jLabelViewMemoryMouseClicked

    private void jLabelAssembleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAssembleMouseClicked
        // TODO add your handling code here:

        String scannedText = jTextAreaCode.getText();
        //       scan.getTextScan(scannedText);
        //       String errorName = error.getErrorMessage();
        //      if(error.getIsError()==true){
            //           JOptionPane.showMessageDialog(this,errorName );
            //      }
        
        String[] arrText = scannedText.split("\n");
        int arrayLast = arrText.length - 1; //number of the last array
        for (int x = 0; x <= arrayLast; x++) {
            isError = false;
            String textArr = arrText[x];
            isAssemble = false;
            int index = textArr.indexOf(" "); //finds if there is spaces :-1 if there is no spaces

            // condition for instructionsets that needs address
            if(textArr.indexOf(":")>0){
                String label = textArr;
                
            }
           
            if (index > 0) {//if there is a space

                String[] strCommand = arrText[x].split(" "); //splits the scanned text(assembly language) into arrays when it has space

                String command = strCommand[0];
                int address = 0;
                if (command.equalsIgnoreCase("load")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }

                }
                if (command.equalsIgnoreCase("save")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }
                }

                if (command.equalsIgnoreCase("org")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }
                }

                if (command.equalsIgnoreCase("db")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }
                }
                if (command.equalsIgnoreCase("jump")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }
                }
                if (command.equalsIgnoreCase("jpos")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }
                }
                if (command.equalsIgnoreCase("jneg")) {
                    try {
                        address = Integer.parseInt(strCommand[1]);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, command + " has no Address");
                        isError = true;
                    }
                }

            } if(index<0){
                if (textArr.equalsIgnoreCase("load")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if (textArr.equalsIgnoreCase("save")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if (textArr.equalsIgnoreCase("org")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if (textArr.equalsIgnoreCase("db")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if (textArr.equalsIgnoreCase("jump")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if (textArr.equalsIgnoreCase("jpos")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if (textArr.equalsIgnoreCase("jneg")) {

                    JOptionPane.showMessageDialog(this, textArr + " has no Address");
                    isError = true;
                }
                if(textArr.isEmpty()){
                    isError=true;
                    JOptionPane.showMessageDialog(this, "You did not write anything :< ");
                }
            }

            
        }
        if (isError == false ){
                JOptionPane.showMessageDialog(this , "Assembled Successfully <3");
                isAssemble= true;
            }

    }//GEN-LAST:event_jLabelAssembleMouseClicked

    private void jLabelViewSystemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewSystemsMouseClicked
        // TODO add your handling code here:
        ViewSystems gui = new ViewSystems();
        gui.show();

    }//GEN-LAST:event_jLabelViewSystemsMouseClicked

    private void jLabelHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHelpMouseClicked
        // TODO add your handling code here:
        
        Help gui = new Help();
        gui.show();
    }//GEN-LAST:event_jLabelHelpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RscpuMenuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RscpuMenuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RscpuMenuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RscpuMenuJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RscpuMenuJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAssemble;
    private javax.swing.JLabel jLabelClearMemory;
    private javax.swing.JLabel jLabelHelp;
    private javax.swing.JLabel jLabelViewMemory;
    private javax.swing.JLabel jLabelViewSystems;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCode;
    // End of variables declaration//GEN-END:variables
}
